// AUTO-GENERATED by scripts/build-related.ts — do not edit by hand.
const RELATED: Record<string, string[]> = {
  "system-macos.screenshot-region": [
    "system-macos.screenshot-tool",
    "system-macos.screenshot-screen",
    "system-linux.screenshot-area"
  ],
  "system-macos.screenshot-screen": [
    "system-macos.screenshot-region",
    "system-macos.screenshot-tool",
    "system-linux.screenshot-screen"
  ],
  "system-macos.screenshot-tool": [
    "system-macos.screenshot-region",
    "system-macos.screenshot-screen"
  ],
  "system-macos.force-quit": [
    "system-macos.hide-app",
    "system-macos.quit-app",
    "system-macos.hide-others"
  ],
  "system-macos.mission-control": [
    "system-macos.hide-app",
    "system-macos.quit-app",
    "system-macos.hide-others"
  ],
  "system-macos.app-switcher": [
    "system-macos.hide-app",
    "system-macos.quit-app",
    "system-macos.hide-others",
    "system-windows.switch-app",
    "system-linux.switch-app"
  ],
  "system-macos.hide-app": [
    "system-macos.quit-app",
    "system-macos.hide-others",
    "system-macos.mission-control"
  ],
  "system-macos.hide-others": [
    "system-macos.hide-app",
    "system-macos.quit-app",
    "system-macos.mission-control"
  ],
  "system-macos.close-window": [
    "system-macos.hide-app",
    "system-macos.quit-app",
    "system-macos.hide-others"
  ],
  "system-macos.quit-app": [
    "system-macos.hide-app",
    "system-macos.hide-others",
    "system-macos.mission-control"
  ],
  "system-macos.lock-screen": [
    "system-macos.sleep-display",
    "system-windows.lock",
    "system-linux.lock",
    "terminal.clear-screen"
  ],
  "system-macos.sleep-display": [
    "system-macos.lock-screen"
  ],
  "system-macos.copy": [
    "system-macos.cut",
    "system-macos.undo",
    "system-macos.redo",
    "system-windows.copy",
    "system-linux.copy",
    "finder.copy"
  ],
  "system-macos.paste": [
    "system-macos.cut",
    "system-macos.copy",
    "system-macos.undo",
    "system-windows.paste",
    "system-linux.paste",
    "finder.paste"
  ],
  "system-macos.cut": [
    "system-macos.copy",
    "system-macos.undo",
    "system-macos.redo",
    "system-windows.cut",
    "system-linux.cut",
    "google-docs.keyboard-shortcuts-help"
  ],
  "system-macos.undo": [
    "system-macos.cut",
    "system-macos.copy",
    "system-macos.redo",
    "system-windows.undo",
    "system-linux.undo",
    "google-docs.underline"
  ],
  "system-macos.redo": [
    "system-macos.cut",
    "system-macos.copy",
    "system-macos.undo",
    "system-windows.redo",
    "system-linux.redo",
    "google-docs.numbered-list"
  ],
  "system-macos.select-all": [
    "system-macos.cut",
    "system-macos.copy",
    "system-macos.undo",
    "system-windows.select-all",
    "system-linux.select-all",
    "vscode.select-next-occurrence"
  ],
  "system-macos.spotlight-finder": [
    "system-macos.hide-app",
    "system-macos.quit-app",
    "system-macos.hide-others"
  ],
  "system-windows.start-menu": [
    "system-windows.settings",
    "system-windows.run",
    "system-windows.task-manager"
  ],
  "system-windows.search": [
    "system-windows.settings",
    "system-windows.start-menu",
    "system-windows.run"
  ],
  "system-windows.run": [
    "system-windows.settings",
    "system-windows.start-menu",
    "system-windows.task-manager"
  ],
  "system-windows.file-explorer": [
    "system-windows.settings",
    "system-windows.start-menu",
    "system-windows.run"
  ],
  "system-windows.settings": [
    "system-windows.start-menu",
    "system-windows.run",
    "system-windows.task-manager"
  ],
  "system-windows.task-manager": [
    "system-windows.settings",
    "system-windows.start-menu",
    "system-windows.run"
  ],
  "system-windows.clipboard-history": [
    "system-windows.cut",
    "system-windows.copy",
    "system-windows.undo"
  ],
  "system-windows.lock": [
    "system-macos.lock-screen",
    "system-linux.lock",
    "terminal.clear-screen"
  ],
  "system-windows.show-desktop": [
    "system-windows.task-view",
    "system-windows.minimize",
    "system-windows.maximize",
    "system-linux.show-desktop"
  ],
  "system-windows.snap-left": [
    "system-windows.show-desktop",
    "system-windows.task-view",
    "system-windows.minimize"
  ],
  "system-windows.snap-right": [
    "system-windows.show-desktop",
    "system-windows.task-view",
    "system-windows.minimize"
  ],
  "system-windows.minimize": [
    "system-windows.show-desktop",
    "system-windows.task-view",
    "system-windows.maximize"
  ],
  "system-windows.maximize": [
    "system-windows.show-desktop",
    "system-windows.task-view",
    "system-windows.minimize"
  ],
  "system-windows.task-view": [
    "system-windows.show-desktop",
    "system-windows.minimize",
    "system-windows.maximize"
  ],
  "system-windows.switch-app": [
    "system-windows.show-desktop",
    "system-windows.task-view",
    "system-windows.minimize",
    "system-linux.switch-app",
    "system-macos.app-switcher"
  ],
  "system-windows.close-window": [
    "system-windows.show-desktop",
    "system-windows.task-view",
    "system-windows.minimize"
  ],
  "system-windows.copy": [
    "system-windows.cut",
    "system-windows.undo",
    "system-windows.redo",
    "system-macos.copy",
    "system-linux.copy",
    "finder.copy"
  ],
  "system-windows.paste": [
    "system-windows.cut",
    "system-windows.copy",
    "system-windows.undo",
    "system-macos.paste",
    "system-linux.paste",
    "finder.paste"
  ],
  "system-windows.cut": [
    "system-windows.copy",
    "system-windows.undo",
    "system-windows.redo",
    "system-macos.cut",
    "system-linux.cut",
    "google-docs.keyboard-shortcuts-help"
  ],
  "system-windows.undo": [
    "system-windows.cut",
    "system-windows.copy",
    "system-windows.redo",
    "system-macos.undo",
    "system-linux.undo",
    "google-docs.underline"
  ],
  "system-windows.redo": [
    "system-windows.cut",
    "system-windows.copy",
    "system-windows.undo",
    "system-macos.redo",
    "system-linux.redo",
    "google-docs.numbered-list"
  ],
  "system-windows.select-all": [
    "system-windows.cut",
    "system-windows.copy",
    "system-windows.undo",
    "system-macos.select-all",
    "system-linux.select-all",
    "vscode.select-next-occurrence"
  ],
  "system-linux.activities": [
    "system-linux.terminal",
    "system-linux.app-grid"
  ],
  "system-linux.app-grid": [
    "system-linux.terminal",
    "system-linux.activities"
  ],
  "system-linux.terminal": [
    "system-linux.app-grid",
    "system-linux.activities",
    "vscode.toggle-terminal"
  ],
  "system-linux.screenshot-area": [
    "system-linux.screenshot-screen",
    "system-macos.screenshot-region"
  ],
  "system-linux.screenshot-screen": [
    "system-linux.screenshot-area",
    "system-macos.screenshot-screen"
  ],
  "system-linux.switch-app": [
    "system-linux.close-window",
    "system-linux.show-desktop",
    "system-linux.workspace-up",
    "system-windows.switch-app",
    "system-macos.app-switcher"
  ],
  "system-linux.switch-window": [
    "system-linux.close-window",
    "system-linux.show-desktop",
    "system-linux.switch-app"
  ],
  "system-linux.close-window": [
    "system-linux.show-desktop",
    "system-linux.switch-app",
    "system-linux.workspace-up",
    "system-windows.close-window"
  ],
  "system-linux.workspace-up": [
    "system-linux.close-window",
    "system-linux.show-desktop",
    "system-linux.switch-app"
  ],
  "system-linux.workspace-down": [
    "system-linux.close-window",
    "system-linux.show-desktop",
    "system-linux.switch-app"
  ],
  "system-linux.show-desktop": [
    "system-linux.close-window",
    "system-linux.switch-app",
    "system-linux.workspace-up",
    "system-windows.show-desktop"
  ],
  "system-linux.lock": [
    "system-linux.logout",
    "system-macos.lock-screen",
    "system-windows.lock",
    "terminal.clear-screen"
  ],
  "system-linux.logout": [
    "system-linux.lock",
    "chrome.zoom-out",
    "firefox.zoom-out",
    "safari.zoom-out"
  ],
  "system-linux.copy": [
    "system-linux.cut",
    "system-linux.undo",
    "system-linux.redo",
    "system-macos.copy",
    "system-windows.copy",
    "finder.copy"
  ],
  "system-linux.paste": [
    "system-linux.cut",
    "system-linux.copy",
    "system-linux.undo",
    "system-macos.paste",
    "system-windows.paste",
    "finder.paste"
  ],
  "system-linux.cut": [
    "system-linux.copy",
    "system-linux.undo",
    "system-linux.redo",
    "system-macos.cut",
    "system-windows.cut",
    "google-docs.keyboard-shortcuts-help"
  ],
  "system-linux.undo": [
    "system-linux.cut",
    "system-linux.copy",
    "system-linux.redo",
    "system-macos.undo",
    "system-windows.undo",
    "google-docs.underline"
  ],
  "system-linux.redo": [
    "system-linux.cut",
    "system-linux.copy",
    "system-linux.undo",
    "system-macos.redo",
    "system-windows.redo",
    "google-docs.numbered-list"
  ],
  "system-linux.select-all": [
    "system-linux.cut",
    "system-linux.copy",
    "system-linux.undo",
    "system-macos.select-all",
    "system-windows.select-all",
    "vscode.select-next-occurrence"
  ],
  "system-linux.paste-terminal": [
    "system-linux.cut",
    "system-linux.copy",
    "system-linux.undo",
    "vscode.toggle-terminal"
  ],
  "chrome.new-tab": [
    "chrome.next-tab",
    "chrome.close-tab",
    "chrome.prev-tab",
    "firefox.new-tab",
    "safari.new-tab",
    "notion.new-page"
  ],
  "chrome.close-tab": [
    "chrome.new-tab",
    "chrome.next-tab",
    "chrome.prev-tab",
    "firefox.close-tab",
    "safari.close-tab",
    "system-windows.close-window"
  ],
  "chrome.reopen-tab": [
    "chrome.new-tab",
    "chrome.next-tab",
    "chrome.close-tab",
    "firefox.reopen-tab",
    "safari.reopen-tab"
  ],
  "chrome.next-tab": [
    "chrome.new-tab",
    "chrome.close-tab",
    "chrome.prev-tab",
    "safari.next-tab",
    "firefox.new-tab"
  ],
  "chrome.prev-tab": [
    "chrome.new-tab",
    "chrome.next-tab",
    "chrome.close-tab",
    "safari.prev-tab",
    "terminal.prev-command",
    "slack.prev-unread"
  ],
  "chrome.focus-address": [
    "chrome.find",
    "chrome.history",
    "chrome.downloads",
    "firefox.focus-address",
    "safari.focus-address"
  ],
  "chrome.find": [
    "chrome.history",
    "chrome.downloads",
    "chrome.focus-address",
    "firefox.find",
    "safari.find"
  ],
  "chrome.history": [
    "chrome.find",
    "chrome.downloads",
    "chrome.focus-address",
    "firefox.history",
    "system-windows.clipboard-history"
  ],
  "chrome.downloads": [
    "chrome.find",
    "chrome.history",
    "chrome.focus-address",
    "firefox.downloads",
    "safari.downloads"
  ],
  "chrome.bookmark": [
    "chrome.find",
    "chrome.history",
    "chrome.downloads",
    "firefox.bookmark"
  ],
  "chrome.devtools": [
    "chrome.inspect",
    "chrome.hard-reload",
    "firefox.devtools"
  ],
  "chrome.inspect": [
    "chrome.devtools",
    "chrome.hard-reload",
    "firefox.inspect"
  ],
  "chrome.hard-reload": [
    "chrome.devtools",
    "chrome.inspect",
    "firefox.hard-reload"
  ],
  "chrome.zoom-in": [
    "chrome.zoom-out",
    "chrome.zoom-reset",
    "chrome.fullscreen",
    "firefox.zoom-in",
    "safari.zoom-in",
    "figma.zoom-fit"
  ],
  "chrome.zoom-out": [
    "chrome.zoom-in",
    "chrome.zoom-reset",
    "chrome.fullscreen",
    "firefox.zoom-out",
    "safari.zoom-out",
    "figma.zoom-fit"
  ],
  "chrome.zoom-reset": [
    "chrome.zoom-in",
    "chrome.zoom-out",
    "chrome.fullscreen"
  ],
  "chrome.fullscreen": [
    "chrome.zoom-in",
    "chrome.zoom-out",
    "chrome.zoom-reset"
  ],
  "firefox.new-tab": [
    "firefox.close-tab",
    "firefox.reopen-tab",
    "chrome.new-tab",
    "safari.new-tab",
    "notion.new-page"
  ],
  "firefox.close-tab": [
    "firefox.new-tab",
    "firefox.reopen-tab",
    "chrome.close-tab",
    "safari.close-tab",
    "system-windows.close-window"
  ],
  "firefox.reopen-tab": [
    "firefox.new-tab",
    "firefox.close-tab",
    "chrome.reopen-tab",
    "safari.reopen-tab"
  ],
  "firefox.focus-address": [
    "firefox.find",
    "firefox.downloads",
    "firefox.focus-search",
    "chrome.focus-address",
    "safari.focus-address"
  ],
  "firefox.focus-search": [
    "firefox.find",
    "firefox.downloads",
    "firefox.focus-address"
  ],
  "firefox.find": [
    "firefox.downloads",
    "firefox.focus-search",
    "firefox.focus-address",
    "chrome.find",
    "safari.find"
  ],
  "firefox.quick-find": [
    "firefox.find",
    "firefox.downloads",
    "firefox.focus-search"
  ],
  "firefox.history": [
    "firefox.find",
    "firefox.downloads",
    "firefox.focus-search"
  ],
  "firefox.downloads": [
    "firefox.find",
    "firefox.focus-search",
    "firefox.focus-address",
    "chrome.downloads",
    "safari.downloads"
  ],
  "firefox.bookmark": [
    "firefox.find",
    "firefox.downloads",
    "firefox.focus-search",
    "chrome.bookmark"
  ],
  "firefox.devtools": [
    "firefox.inspect",
    "firefox.hard-reload",
    "chrome.devtools"
  ],
  "firefox.inspect": [
    "firefox.devtools",
    "firefox.hard-reload",
    "chrome.inspect"
  ],
  "firefox.hard-reload": [
    "firefox.devtools",
    "firefox.inspect",
    "chrome.hard-reload"
  ],
  "firefox.private": [
    "safari.private"
  ],
  "firefox.zoom-in": [
    "firefox.zoom-out",
    "firefox.reader-view",
    "chrome.zoom-in",
    "safari.zoom-in",
    "figma.zoom-fit"
  ],
  "firefox.zoom-out": [
    "firefox.zoom-in",
    "firefox.reader-view",
    "chrome.zoom-out",
    "safari.zoom-out",
    "figma.zoom-fit"
  ],
  "firefox.reader-view": [
    "firefox.zoom-in",
    "firefox.zoom-out",
    "safari.reader-view"
  ],
  "safari.new-tab": [
    "safari.next-tab",
    "safari.close-tab",
    "safari.prev-tab",
    "chrome.new-tab",
    "firefox.new-tab",
    "notion.new-page"
  ],
  "safari.close-tab": [
    "safari.new-tab",
    "safari.next-tab",
    "safari.prev-tab",
    "chrome.close-tab",
    "firefox.close-tab",
    "system-windows.close-window"
  ],
  "safari.reopen-tab": [
    "safari.new-tab",
    "safari.next-tab",
    "safari.close-tab",
    "chrome.reopen-tab",
    "firefox.reopen-tab"
  ],
  "safari.next-tab": [
    "safari.new-tab",
    "safari.close-tab",
    "safari.prev-tab",
    "chrome.next-tab",
    "firefox.new-tab"
  ],
  "safari.prev-tab": [
    "safari.new-tab",
    "safari.next-tab",
    "safari.close-tab",
    "chrome.prev-tab",
    "terminal.prev-command",
    "slack.prev-unread"
  ],
  "safari.focus-address": [
    "safari.find",
    "safari.bookmark",
    "safari.downloads",
    "chrome.focus-address",
    "firefox.focus-address"
  ],
  "safari.find": [
    "safari.bookmark",
    "safari.downloads",
    "safari.history",
    "chrome.find",
    "firefox.find"
  ],
  "safari.history": [
    "safari.find",
    "safari.bookmark",
    "safari.downloads"
  ],
  "safari.downloads": [
    "safari.find",
    "safari.bookmark",
    "safari.history",
    "chrome.downloads",
    "firefox.downloads"
  ],
  "safari.bookmark": [
    "safari.find",
    "safari.downloads",
    "safari.history"
  ],
  "safari.reader-view": [
    "safari.zoom-in",
    "safari.zoom-out",
    "firefox.reader-view"
  ],
  "safari.private": [
    "firefox.private"
  ],
  "safari.show-tab-overview": [
    "safari.new-tab",
    "safari.next-tab",
    "safari.close-tab"
  ],
  "safari.zoom-in": [
    "safari.zoom-out",
    "safari.reader-view",
    "chrome.zoom-in",
    "firefox.zoom-in",
    "figma.zoom-fit"
  ],
  "safari.zoom-out": [
    "safari.zoom-in",
    "safari.reader-view",
    "chrome.zoom-out",
    "firefox.zoom-out",
    "figma.zoom-fit"
  ],
  "vscode.command-palette": [
    "vscode.go-to-line",
    "vscode.quick-open",
    "vscode.go-to-definition",
    "cursor.command-palette"
  ],
  "vscode.quick-open": [
    "vscode.go-to-line",
    "vscode.go-to-definition",
    "vscode.command-palette",
    "cursor.quick-open"
  ],
  "vscode.go-to-line": [
    "vscode.quick-open",
    "vscode.go-to-definition",
    "vscode.command-palette",
    "linear.go-inbox",
    "finder.go-up"
  ],
  "vscode.go-to-symbol": [
    "vscode.go-to-line",
    "vscode.quick-open",
    "vscode.go-to-definition"
  ],
  "vscode.go-to-definition": [
    "vscode.go-to-line",
    "vscode.quick-open",
    "vscode.command-palette"
  ],
  "vscode.toggle-terminal": [
    "vscode.split-editor",
    "vscode.toggle-sidebar"
  ],
  "vscode.toggle-sidebar": [
    "vscode.split-editor",
    "vscode.toggle-terminal",
    "notion.toggle-sidebar",
    "firefox.history"
  ],
  "vscode.split-editor": [
    "vscode.toggle-sidebar",
    "vscode.toggle-terminal"
  ],
  "vscode.multi-cursor-below": [
    "vscode.move-line-up",
    "vscode.rename-symbol",
    "vscode.move-line-down"
  ],
  "vscode.multi-cursor-above": [
    "vscode.move-line-up",
    "vscode.rename-symbol",
    "vscode.move-line-down"
  ],
  "vscode.select-next-occurrence": [
    "vscode.move-line-up",
    "vscode.rename-symbol",
    "vscode.move-line-down"
  ],
  "vscode.rename-symbol": [
    "vscode.move-line-up",
    "vscode.move-line-down",
    "vscode.duplicate-line"
  ],
  "vscode.format-document": [
    "vscode.move-line-up",
    "vscode.rename-symbol",
    "vscode.move-line-down"
  ],
  "vscode.comment-line": [
    "vscode.move-line-up",
    "vscode.rename-symbol",
    "vscode.move-line-down"
  ],
  "vscode.move-line-down": [
    "vscode.move-line-up",
    "vscode.rename-symbol",
    "vscode.duplicate-line"
  ],
  "vscode.move-line-up": [
    "vscode.rename-symbol",
    "vscode.move-line-down",
    "vscode.duplicate-line"
  ],
  "vscode.duplicate-line": [
    "vscode.move-line-up",
    "vscode.rename-symbol",
    "vscode.move-line-down"
  ],
  "vscode.find": [
    "vscode.replace",
    "vscode.find-in-files"
  ],
  "vscode.replace": [
    "vscode.find",
    "vscode.find-in-files"
  ],
  "vscode.find-in-files": [
    "vscode.find",
    "vscode.replace"
  ],
  "vscode.zen-mode": [
    "figma.dev-mode",
    "notion.dark-mode"
  ],
  "cursor.ai-chat": [
    "cursor.composer",
    "cursor.inline-edit",
    "cursor.accept-suggestion"
  ],
  "cursor.inline-edit": [
    "cursor.ai-chat",
    "cursor.composer",
    "cursor.accept-suggestion"
  ],
  "cursor.composer": [
    "cursor.ai-chat",
    "cursor.inline-edit",
    "cursor.accept-suggestion"
  ],
  "cursor.accept-suggestion": [
    "cursor.ai-chat",
    "cursor.composer",
    "cursor.inline-edit"
  ],
  "cursor.reject-suggestion": [
    "cursor.ai-chat",
    "cursor.composer",
    "cursor.inline-edit"
  ],
  "cursor.quick-open": [
    "cursor.command-palette",
    "vscode.quick-open"
  ],
  "cursor.command-palette": [
    "cursor.quick-open",
    "vscode.command-palette"
  ],
  "terminal.start-of-line": [
    "terminal.clear-screen",
    "terminal.delete-word",
    "terminal.end-of-line"
  ],
  "terminal.end-of-line": [
    "terminal.clear-screen",
    "terminal.delete-word",
    "terminal.start-of-line"
  ],
  "terminal.clear-screen": [
    "terminal.delete-word",
    "terminal.end-of-line",
    "terminal.start-of-line",
    "system-macos.screenshot-screen",
    "system-linux.screenshot-screen"
  ],
  "terminal.delete-word": [
    "terminal.clear-screen",
    "terminal.end-of-line",
    "terminal.start-of-line"
  ],
  "terminal.search-history": [
    "terminal.prev-command",
    "system-windows.clipboard-history"
  ],
  "terminal.prev-command": [
    "terminal.search-history"
  ],
  "terminal.cancel": [
    "terminal.eof",
    "terminal.suspend"
  ],
  "terminal.eof": [
    "terminal.suspend",
    "terminal.cancel"
  ],
  "terminal.suspend": [
    "terminal.eof",
    "terminal.cancel"
  ],
  "slack.quick-switcher": [
    "slack.search",
    "slack.preferences",
    "slack.threads"
  ],
  "slack.search": [
    "slack.preferences",
    "slack.threads",
    "slack.dms"
  ],
  "slack.preferences": [
    "slack.search",
    "slack.threads",
    "slack.dms"
  ],
  "slack.mark-all-read": [
    "slack.next-unread",
    "slack.mark-channel-read",
    "slack.prev-unread"
  ],
  "slack.mark-channel-read": [
    "slack.next-unread",
    "slack.prev-unread",
    "slack.mark-all-read"
  ],
  "slack.next-unread": [
    "slack.mark-channel-read",
    "slack.prev-unread",
    "slack.mark-all-read"
  ],
  "slack.prev-unread": [
    "slack.next-unread",
    "slack.mark-channel-read",
    "slack.mark-all-read"
  ],
  "slack.threads": [
    "slack.search",
    "slack.preferences",
    "slack.dms",
    "system-windows.task-view"
  ],
  "slack.dms": [
    "slack.search",
    "slack.preferences",
    "slack.threads"
  ],
  "slack.activity": [
    "slack.search",
    "slack.preferences",
    "slack.threads"
  ],
  "slack.edit-last": [
    "slack.bold",
    "slack.italic",
    "slack.code"
  ],
  "slack.react": [
    "slack.bold",
    "slack.italic",
    "slack.code"
  ],
  "slack.bold": [
    "slack.italic",
    "slack.code",
    "slack.upload"
  ],
  "slack.italic": [
    "slack.bold",
    "slack.code",
    "slack.upload"
  ],
  "slack.code": [
    "slack.bold",
    "slack.italic",
    "slack.upload",
    "notion.inline-code",
    "cursor.inline-edit"
  ],
  "slack.upload": [
    "slack.bold",
    "slack.italic",
    "slack.code"
  ],
  "notion.new-page": [
    "notion.quick-find",
    "notion.toggle-sidebar",
    "notion.dark-mode",
    "chrome.find",
    "firefox.find",
    "safari.find"
  ],
  "notion.quick-find": [
    "notion.new-page",
    "notion.toggle-sidebar",
    "notion.dark-mode",
    "firefox.quick-find"
  ],
  "notion.toggle-sidebar": [
    "notion.new-page",
    "notion.quick-find",
    "notion.dark-mode",
    "vscode.toggle-sidebar",
    "firefox.history"
  ],
  "notion.dark-mode": [
    "notion.new-page",
    "notion.quick-find",
    "notion.toggle-sidebar",
    "figma.dev-mode",
    "vscode.zen-mode"
  ],
  "notion.heading-1": [
    "notion.heading-2",
    "notion.bullet-list",
    "google-docs.heading-1"
  ],
  "notion.heading-2": [
    "notion.heading-1",
    "notion.bullet-list",
    "google-docs.heading-2"
  ],
  "notion.bullet-list": [
    "notion.heading-1",
    "notion.heading-2",
    "google-docs.bulleted-list"
  ],
  "notion.bold": [
    "notion.italic",
    "notion.inline-code",
    "google-docs.bold",
    "slack.bold",
    "vscode.rename-symbol"
  ],
  "notion.italic": [
    "notion.bold",
    "notion.inline-code",
    "google-docs.italic",
    "slack.italic"
  ],
  "notion.inline-code": [
    "notion.bold",
    "notion.italic",
    "slack.code",
    "cursor.inline-edit"
  ],
  "linear.create-issue": [
    "linear.assign-me",
    "linear.set-priority"
  ],
  "linear.command-menu": [
    "linear.search",
    "linear.go-inbox",
    "linear.go-my-issues"
  ],
  "linear.go-inbox": [
    "linear.search",
    "linear.command-menu",
    "linear.go-my-issues"
  ],
  "linear.go-my-issues": [
    "linear.search",
    "linear.go-inbox",
    "linear.command-menu"
  ],
  "linear.assign-me": [
    "linear.create-issue",
    "linear.set-priority"
  ],
  "linear.set-priority": [
    "linear.create-issue",
    "linear.assign-me"
  ],
  "linear.search": [
    "linear.go-inbox",
    "linear.command-menu",
    "linear.go-my-issues",
    "terminal.search-history",
    "slack.search",
    "system-macos.spotlight"
  ],
  "figma.frame": [
    "figma.pen",
    "figma.text",
    "figma.comment"
  ],
  "figma.rectangle": [
    "figma.pen",
    "figma.text",
    "figma.frame"
  ],
  "figma.text": [
    "figma.pen",
    "figma.frame",
    "figma.comment"
  ],
  "figma.pen": [
    "figma.text",
    "figma.frame",
    "figma.comment"
  ],
  "figma.hand": [
    "figma.pen",
    "figma.text",
    "figma.frame"
  ],
  "figma.comment": [
    "figma.pen",
    "figma.text",
    "figma.frame"
  ],
  "figma.group": [
    "figma.ungroup"
  ],
  "figma.ungroup": [
    "figma.group"
  ],
  "figma.create-component": [
    "figma.detach-instance"
  ],
  "figma.detach-instance": [
    "figma.create-component"
  ],
  "figma.zoom-fit": [
    "figma.zoom-100",
    "figma.toggle-ui",
    "figma.dev-mode"
  ],
  "figma.zoom-100": [
    "figma.zoom-fit",
    "figma.toggle-ui",
    "figma.dev-mode"
  ],
  "figma.zoom-selection": [
    "figma.zoom-fit",
    "figma.zoom-100",
    "figma.toggle-ui"
  ],
  "figma.toggle-ui": [
    "figma.zoom-fit",
    "figma.zoom-100",
    "figma.dev-mode"
  ],
  "figma.layers-panel": [
    "figma.zoom-fit",
    "figma.zoom-100",
    "figma.toggle-ui"
  ],
  "figma.dev-mode": [
    "figma.zoom-fit",
    "figma.zoom-100",
    "figma.toggle-ui",
    "vscode.zen-mode",
    "notion.dark-mode"
  ],
  "google-docs.bold": [
    "google-docs.italic",
    "google-docs.underline",
    "google-docs.strikethrough",
    "notion.bold",
    "slack.bold",
    "vscode.rename-symbol"
  ],
  "google-docs.italic": [
    "google-docs.bold",
    "google-docs.underline",
    "google-docs.strikethrough",
    "notion.italic",
    "slack.italic"
  ],
  "google-docs.underline": [
    "google-docs.bold",
    "google-docs.italic",
    "google-docs.strikethrough"
  ],
  "google-docs.strikethrough": [
    "google-docs.bold",
    "google-docs.italic",
    "google-docs.underline"
  ],
  "google-docs.clear-formatting": [
    "google-docs.bold",
    "google-docs.italic",
    "google-docs.underline"
  ],
  "google-docs.heading-1": [
    "google-docs.bold",
    "google-docs.italic",
    "google-docs.underline"
  ],
  "google-docs.heading-2": [
    "google-docs.bold",
    "google-docs.italic",
    "google-docs.underline"
  ],
  "google-docs.normal-text": [
    "google-docs.bold",
    "google-docs.italic",
    "google-docs.underline"
  ],
  "google-docs.link": [
    "google-docs.comment",
    "google-docs.footnote"
  ],
  "google-docs.comment": [
    "google-docs.footnote",
    "google-docs.link",
    "vscode.comment-line"
  ],
  "google-docs.footnote": [
    "google-docs.comment",
    "google-docs.link"
  ],
  "google-docs.bulleted-list": [
    "google-docs.checklist",
    "google-docs.numbered-list",
    "notion.bullet-list"
  ],
  "google-docs.numbered-list": [
    "google-docs.checklist",
    "google-docs.bulleted-list"
  ],
  "google-docs.checklist": [
    "google-docs.bulleted-list",
    "google-docs.numbered-list"
  ],
  "google-docs.find": [
    "google-docs.find-replace"
  ],
  "google-docs.find-replace": [
    "google-docs.find"
  ],
  "google-docs.word-count": [
    "google-docs.voice-typing"
  ],
  "google-docs.voice-typing": [
    "google-docs.word-count"
  ],
  "finder.new-folder": [
    "finder.copy",
    "finder.rename",
    "finder.paste"
  ],
  "finder.rename": [
    "finder.copy",
    "finder.new-folder",
    "finder.paste",
    "vscode.rename-symbol"
  ],
  "finder.delete": [
    "finder.copy",
    "finder.rename",
    "finder.new-folder"
  ],
  "finder.get-info": [
    "finder.copy",
    "finder.rename",
    "finder.new-folder"
  ],
  "finder.copy": [
    "finder.rename",
    "finder.new-folder",
    "finder.paste",
    "system-macos.copy",
    "system-windows.copy",
    "system-linux.copy"
  ],
  "finder.paste": [
    "finder.copy",
    "finder.rename",
    "finder.new-folder"
  ],
  "finder.go-up": [
    "finder.open"
  ],
  "finder.open": [
    "finder.go-up"
  ]
};

export function getRelated(id: string): string[] {
  return RELATED[id] ?? [];
}
