import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import Fuse from "fuse.js";
import { SHORTCUTS } from "../src/data";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, "../src/data/_generated/related.ts");

const fuse = new Fuse(SHORTCUTS, {
  keys: ["function"],
  threshold: 0.3,
  ignoreLocation: true,
  minMatchCharLength: 3,
});

const RELATED: Record<string, string[]> = {};

for (const s of SHORTCUTS) {
  const sameAppCat = SHORTCUTS.filter(
    (o) => o.id !== s.id && o.appId === s.appId && o.category && o.category === s.category,
  )
    .sort((a, b) => a.function.length - b.function.length)
    .slice(0, 3)
    .map((o) => o.id);

  const crossAppMatches = fuse.search(s.function);
  const seen = new Set<string>([s.appId]);
  const crossApp: string[] = [];
  for (const m of crossAppMatches) {
    if (m.item.id === s.id) continue;
    if (seen.has(m.item.appId)) continue;
    seen.add(m.item.appId);
    crossApp.push(m.item.id);
    if (crossApp.length >= 3) break;
  }

  const merged: string[] = [];
  for (const id of [...sameAppCat, ...crossApp]) {
    if (!merged.includes(id)) merged.push(id);
    if (merged.length >= 6) break;
  }

  if (merged.length > 0) RELATED[s.id] = merged;
}

mkdirSync(dirname(OUT), { recursive: true });

const body = `// AUTO-GENERATED by scripts/build-related.ts — do not edit by hand.
const RELATED: Record<string, string[]> = ${JSON.stringify(RELATED, null, 2)};

export function getRelated(id: string): string[] {
  return RELATED[id] ?? [];
}
`;

writeFileSync(OUT, body, "utf8");
console.log(`Wrote ${OUT} (${Object.keys(RELATED).length} shortcuts with related entries)`);
